### ISSUE TITLE
Unreliable order of plugins listed under options.plugins

### ISSUE THREAD

**Issue by ArnaudBarre** [prettier/prettier-cli#5] opened 2023-12-01 21:20 UTC
I have my configuration in my package.json with `"plugins": ["@prettier/plugin-xml"]` and the CLI errors `src/icons/trash.svg: UndefinedParserError: No parser could be inferred for file`

**Comment by fabiospampinato** [comment] 2023-12-01 21:28
Plugins have not been wired back at the moment, it's maybe the main thing missing. 

For use cases like yours it should be easy to get them to work, but for dynamically defined plugins, like via `.prettierrc.js` files, it may be much more difficult in general, maybe some things should be changed there for performance.

**Comment by fabiospampinato** [comment] 2023-12-16 15:53
@ArnaudBarre In the latest alpha plugins should be supported, unless you pre-instantiate them in a `*.{js|cjs|mjs}` file, which I'd imagine most people don't do. Could you check if it works for you?

**Comment by ArnaudBarre** [comment] 2023-12-16 18:36
Nope not working for me with `0.2.1`
```
arnaud@Mac carbon-calculator-main % bun prettier --write '**/*.{ts,tsx,js,html,css,json,md,yaml,prisma,svg}'
[error] prisma/schema.prisma: UndefinedParserError: No parser could be inferred for file "/Users/arnaud/git/carbon-calculator-main/prisma/schema.prisma".
[error] src/components/PublicPageWrapper/graphic.svg: UndefinedParserError: No parser could be inferred for file "/Users/arnaud/git/carbon-calculator-main/src/components/PublicPageWrapper/graphic.svg".
```

My config in `package.json` (correctly resolved I tried to update printWidth):
```json
{
  "prettier": {
    "xmlWhitespaceSensitivity": "ignore",
    "plugins": [
      "@arnaud-barre/prettier-plugin-sort-imports",
      "@prettier/plugin-xml",
      "prettier-plugin-prisma"
    ]
  },
}
```

**Comment by fabiospampinato** [comment] 2023-12-16 21:52
Ah sorry it looks like I had only implemented it when configured entirely through the CLI, there are a bunch of extra things to take care of for your use case.

**Comment by fabiospampinato** [comment] 2023-12-21 16:15
@ArnaudBarre could you check if alpha8 fixed all the issues for you?

**Comment by ArnaudBarre** [comment] 2023-12-22 17:02
So now it works for SVG/prisma, but the new CLI makes `options.plugins` in plugins a lot longer with item likes
```json
  {
    "parsers": {
      "acorn": {
        "astFormat": "estree"
      },
      "espree": {
        "astFormat": "estree"
      }
    }
  },
```

I don't think this is part of the plugin API and I don't mind updating [my hacky code](https://github.com/ArnaudBarre/prettier-plugin-sort-imports/blob/main/src/index.ts#L13), just wanting to let you know in case it might be an unwanted change

**Comment by fabiospampinato** [comment] 2023-12-22 17:13
Do you get a "Non-string plugin specifiers are not supported yet" error if you just don't change your configuration at all?

**Comment by ArnaudBarre** [comment] 2023-12-22 17:31
Nope I get `TypeError: Cannot read properties of undefined (reading 'estree')` because the first item of the list is not anymore the main plugin with all the config and is the one in the previous comment

**Comment by fabiospampinato** [comment] 2023-12-22 17:35
So it's probably an error 🤔 I'm not sure I'm understanding the scenario exactly though, does the previous repro that you made reproduce this?

**Comment by ArnaudBarre** [comment] 2023-12-22 17:41
You should be able to reproduce the issue by running the latest version with https://github.com/ArnaudBarre/prettier-plugin-sort-imports on a simple TS file.

**Comment by fabiospampinato** [comment] 2024-04-19 15:08
I've taken a closer look at this last error you hit, I think I would basically classify it as user error, because [here](https://github.com/ArnaudBarre/prettier-plugin-sort-imports/blob/ddffdd48e908b43c60c9ae78ae3a94a81403862d/src/index.ts#L13) you are making the assumption that the first plugin is going to be a specific one, basically, while that seems an implementation detail with no specific guarantees, so you shouldn't rely on that. 

I see [a couple of other projects](https://github.com/search?q=options.plugins%5B0%5D.printers&type=code) potentially making the same assumptions, but presumably most users would be unaffected.

There could be more to this potentially, Prettier internally seems to use a function for generating a sort of single merged plugin which points to all the built-in plugins, and that's what you are referencing with that `options.plugins[0]`, it's possible that doing it differently could break something else, but for now I don't see any actual clear errors in the current implementation in that regard.

**Comment by fabiospampinato** [comment] 2024-04-19 15:11
Ah it's basically a performance optimization that Prettier is doing, to lazy-load built-in plugins as needed, which I actually wanted to do also but didn't know how to do it. I guess I can implement that and that should also accidentally fix your use case.

**Comment by fbartho** [comment] 2024-04-19 16:11
@fabiospampinato — I personally would think that assuming `plugins[0]` is a specific problem is brittle/naive.

I would however expect that plugins are in a linear order. If you wanted to say  “instead of accessing `.plugins` you should request plugins by `id` or provide use a`filter` method that matches for the plugin you need, I think that would be fine.

Eg. 
```js
let esTreePlugin = options.plugins.findFirst((plugin)->{
  return plugin.estree != nil
}
…
```

**Comment by fabiospampinato** [comment] 2024-04-19 18:00
closing as [this commmit](https://github.com/prettier/prettier-cli/commit/88076b5809a84cc2a39f7a736f8edbddd4a3af2e) kinda accidentally fixes this, by loading built-in plugins ~exactly like the stable CLI does it. 

I'll take a look at #5 and I'll try to push another release 🙂

**Closed by fabiospampinato** 2024-04-19 18:00 UTC
Labels: bug, maybe

**Comment by fabiospampinato** [comment] 2024-04-27 21:20
@ArnaudBarre As soon as somebody is able to release `-beta.0` you should be able to check for yourself if it fixes your problem or not. Sorry for the long wait, lots of things going on 🤪

**Comment by ArnaudBarre** [comment] 2024-04-28 08:48
Yeah no problem, thanks for your work!
